### ISSUE TITLE
Why use div instead of HTMLPanel ?

### ISSUE THREAD

**Issue by OrNot** [gwidgets/gwt-polymer-starter-kit#1]
Hi, I notice your code in UiBinder  where you are using  div  other than htmlpanel as the container  . 
In the java code:

   interface MainPageUiBinder extends UiBinder<Element, MainPage> {
    }

```
public MainPage() {
    setElement(uiBinder.createAndBindUi(this));

    Polymer.endLoading(this.getElement(), (Element) paperMenu);
}
```

   you use Element and SetElement .   

   Is there any consideration here than  the old HTMLPanel  ?   

  T.I.A

**Comment by zak905** [comment]
I have not really thought about it, I have been using this pattern a lot lately, so  just a reflex :) 

but now that you mentionned it, I think that performance wise, you loose on performance while using HTMLPanel over a native Dom element because GWT converts it to several nested elements. You can use -gen flag when compiling to compare the generated code for both.

Zakaria

**Comment by OrNot** [comment]
Thanks for your reply. I am new to polymer so I have to study your codes line by line. Now it is clear.
